# Cloud Build config for serving image
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/mlops-lab/serving:${_TAG}'
      - '-f'
      - 'Dockerfile.serving'
      - '.'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/mlops-lab/serving:${_TAG}'

substitutions:
  _REGION: us-central1
  _TAG: v1
